"""empty message

Revision ID: 00d963d4d565
Revises: 2bb765b1fcde
Create Date: 2021-04-08 03:19:26.977264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00d963d4d565'
down_revision = '2bb765b1fcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'eye_color')
    op.drop_column('character', 'hair_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('hair_color', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('eye_color', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
