"""empty message

Revision ID: 2392d639d68a
Revises: e9d21bc4cb8d
Create Date: 2021-04-10 02:20:18.294188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2392d639d68a'
down_revision = 'e9d21bc4cb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_chars',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('fav_planets',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_constraint('characters_ibfk_1', 'characters', type_='foreignkey')
    op.drop_column('characters', 'user_id')
    op.drop_constraint('planets_ibfk_1', 'planets', type_='foreignkey')
    op.drop_column('planets', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('planets_ibfk_1', 'planets', 'users', ['user_id'], ['id'])
    op.add_column('characters', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('characters_ibfk_1', 'characters', 'users', ['user_id'], ['id'])
    op.drop_table('fav_planets')
    op.drop_table('fav_chars')
    # ### end Alembic commands ###
