"""empty message

Revision ID: 2839ac6b60ac
Revises: 2392d639d68a
Create Date: 2021-04-11 20:11:06.781978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2839ac6b60ac'
down_revision = '2392d639d68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('birth_year', sa.String(length=250), nullable=False))
    op.add_column('characters', sa.Column('eye_color', sa.String(length=250), nullable=False))
    op.add_column('characters', sa.Column('gender', sa.String(length=250), nullable=False))
    op.add_column('characters', sa.Column('hair_color', sa.String(length=250), nullable=False))
    op.add_column('characters', sa.Column('height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'height')
    op.drop_column('characters', 'hair_color')
    op.drop_column('characters', 'gender')
    op.drop_column('characters', 'eye_color')
    op.drop_column('characters', 'birth_year')
    # ### end Alembic commands ###
