"""empty message

Revision ID: 57e549a6c1a6
Revises: 2e924226c2ec
Create Date: 2021-04-08 03:29:02.887217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57e549a6c1a6'
down_revision = '2e924226c2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('eye_color', sa.String(length=250), nullable=False))
    op.add_column('character', sa.Column('hair_color', sa.String(length=250), nullable=False))
    op.drop_column('character', 'eyeColor')
    op.drop_column('character', 'hairColor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('hairColor', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('character', sa.Column('eyeColor', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('character', 'hair_color')
    op.drop_column('character', 'eye_color')
    # ### end Alembic commands ###
