"""empty message

Revision ID: 62abce5e6660
Revises: 762402052503
Create Date: 2021-04-08 02:37:10.411664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62abce5e6660'
down_revision = '762402052503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('lastname', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    op.drop_column('user', 'name')
    op.drop_column('user', 'lastname')
    op.drop_table('character')
    # ### end Alembic commands ###
