"""empty message

Revision ID: 7887ca4c43f2
Revises: 41791f629f35
Create Date: 2021-04-08 21:35:27.982452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7887ca4c43f2'
down_revision = '41791f629f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'birth_year')
    op.drop_column('character', 'hair_color')
    op.drop_column('character', 'height')
    op.drop_column('character', 'eye_color')
    op.drop_column('character', 'gender')
    op.drop_column('planet', 'birth_year')
    op.drop_column('planet', 'hair_color')
    op.drop_column('planet', 'height')
    op.drop_column('planet', 'eye_color')
    op.drop_column('planet', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('gender', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('planet', sa.Column('eye_color', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('planet', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('planet', sa.Column('hair_color', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('planet', sa.Column('birth_year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('gender', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('character', sa.Column('eye_color', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('character', sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('character', sa.Column('hair_color', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('character', sa.Column('birth_year', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
