"""empty message

Revision ID: 7ad41ae311a5
Revises: 00d963d4d565
Create Date: 2021-04-08 03:23:01.745109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad41ae311a5'
down_revision = '00d963d4d565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('eye_color', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'eye_color')
    # ### end Alembic commands ###
