"""empty message

Revision ID: e0d104ce45af
Revises: 2839ac6b60ac
Create Date: 2021-04-11 21:24:30.009830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d104ce45af'
down_revision = '2839ac6b60ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('climate', sa.String(length=250), nullable=False))
    op.add_column('planets', sa.Column('diameter', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('orbital_period', sa.Integer(), nullable=False))
    op.add_column('planets', sa.Column('population', sa.String(length=250), nullable=False))
    op.add_column('planets', sa.Column('rotation_period', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'population')
    op.drop_column('planets', 'orbital_period')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'climate')
    # ### end Alembic commands ###
