"""empty message

Revision ID: e9d21bc4cb8d
Revises: cdb0e616ca83
Create Date: 2021-04-09 23:40:23.779289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9d21bc4cb8d'
down_revision = 'cdb0e616ca83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'users', ['user_id'], ['id'])
    op.add_column('planets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'planets', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'character_id')
    op.drop_column('users', 'planet_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('character_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'characters', ['character_id'], ['id'])
    op.create_foreign_key('users_ibfk_2', 'users', 'planets', ['planet_id'], ['id'])
    op.drop_constraint(None, 'planets', type_='foreignkey')
    op.drop_column('planets', 'user_id')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'user_id')
    # ### end Alembic commands ###
